name: 'action-vendir'
description: 'Executes vendir with provided args'
branding:
  icon: 'align-justify'
  color: 'blue'
inputs:
  token:
    description: GitHub token to authenticate `git clone` requests. REQUIRED
    required: true
  version:
    description: Version of `vendir` to install. OPTIONAL, defaults to `latest`
    required: false
    default: "latest"
  locked:
    description: Whether or not vendir should be invoked with `--locked` option. OPTIONAL, defaults to "false"
    required: false
    default: "false"
  vendir_file:
    description: File that defines dependencies. OPTIONAL, defaults to "vendir.yml"
    required: false
    default: "vendir.yml"
  working_dir:
    description: Working directory to switch to prior to running vendir, defaults to "."
    required: false
    default: "."
runs:
  using: 'node12'
  main: 'index.js'
