name: Test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - name: create vendir.yml
        run: |
          cat >vendir.yml <<EOL
          apiVersion: vendir.k14s.io/v1alpha1
          kind: Config
          directories:
          - path: vendor
            contents:
            - path: github.com/zendesk/jsonnet-kubernetes/
              git:
                url: git@github.com:zendesk/jsonnet-kubernetes.git
                ref: origin/master
              includePaths:
                - 'lib/K8s.libsonnet'
          EOL
      - name: Execute vendir
        uses: ./
        with:
          token: ${{ secrets.GLOVER_ACCESS_TOKEN }}
      - name: verify vendir.lock.yml
        run: |
          cat vendir.lock.yml
      - name: verify vendored directory
        run: |
          ls vendor/github.com/zendesk/jsonnet-kubernetes/lib/
  
  test-working-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v2
      - name: create vendir.yml
        working-directory: kubernetes
        run: |
            cat >vendir.yml <<EOL
            apiVersion: vendir.k14s.io/v1alpha1
            kind: Config
            directories:
            - path: vendor
              contents:
              - path: github.com/zendesk/jsonnet-kubernetes/
                git:
                  url: git@github.com:zendesk/jsonnet-kubernetes.git
                  ref: origin/master
                includePaths:
                  - 'lib/K8s.libsonnet'
            EOL
      - name: Execute vendir
        uses: ./
        with:
          token: ${{ secrets.GLOVER_ACCESS_TOKEN }}
          working_dir: kubernetes
      - name: verify vendir.lock.yml
        working-directory: kubernetes
        run: |
          cat vendir.lock.yml
      - name: verify vendored directory
        working-directory: kubernetes
        run: |
          ls vendor/github.com/zendesk/jsonnet-kubernetes/lib/
